apiVersion: apps/v1
kind: Deployment
metadata:
  name: api
  labels:
    app: api
spec:
  replicas: 3
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      name: api
      labels:
        app: api
    spec:
      containers:
        - name: api
          securityContext:
            readOnlyRootFilesystem: true
            capabilities:
              drop:
                - ALL
          image: alex23451234/django-api:latest
          imagePullPolicy: IfNotPresent
          volumeMounts:
            - mountPath: /certs
              name: certs
            - mountPath: /etc/redis
              name: redis
      restartPolicy: Always
---

apiVersion: v1
kind: Service
metadata:
  name: api-service
spec:
  selector:
    app: api
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: LoadBalancer
