apiVersion: apps/v1
kind: Deployment
metadata:
  name: api
  labels:
    app: api
spec:
  replicas: 3
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      name: api
      labels:
        app: api
    spec:
      securityContext:
        runAsUser: 1000
        runAsGroup: 1000
      containers:
        - name: api
          securityContext:
            capabilities:
              drop:
                - ALL
          image: alex23451234/django-api:latest
          imagePullPolicy: Always
          volumeMounts:
            - mountPath: /etc/secrets/certs
              name: certs
              readOnly: true
              subPath: certs

            - mountPath: /etc/secrets
              name: password
              readOnly: true
      volumes:
        - name: certs
          secret:
            secretName: db-postgresql-crt
            items:
              - key: ca.crt
                path: ca.crt
              - key: tls.crt
                path: tls.crt
              - key: tls.key
                path: tls.key

        - name: password
          secret:
            secretName: db-postgresql
            items:
              - key: postgres-password
                path: password

      restartPolicy: Always

---

apiVersion: v1
kind: Service
metadata:
  name: api-service
spec:
  selector:
    app: api
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
  type: ClusterIP
