name: rollback
on:
  workflow_dispatch:
    inputs:
      branch:
        description: 'Branch name'
        required: true
        default: 'master'
jobs:
  revert_commit:
    runs-on: ubuntu-latest
    steps:
        - name: Checkout branch
          uses: actions/checkout@v3
          with:
            ref: ${{ github.event.inputs.branch }}
            fetch-depth: 0
        - name: Revert pushed commit
          run: |
              git config --global user.name 'github-actions[bot]'
              git config --global user.email 'github-actions[bot]@users.noreply.github.com'
              git revert --no-edit HEAD
              git push
  run_another_workflow:
    runs-on: ubuntu-latest
    needs: revert_commit
    steps:
      - name: Trigger another workflow
        run: |
          curl -X POST \
          -H "Accept: application/vnd.github+json" \
          -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
          https://api.github.com/repos/${{ github.repository }}/actions/workflows/release/dispatches \
          -d '{"ref": "${{ github.event.inputs.branch }}"}'